### ISSUE TITLE
Can't generate 'EventEmitter' error

### ISSUE THREAD

**Issue by ValentinCreative** [dwightjack/grunt-premailer#21]
Hi, 

when i try to generate my emails, I got this error : 
 ```
Running "premailer:simple" (premailer) task
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace:
  at WriteStream.EventEmitter.addListener (events.js:160:15)
  at WriteStream.Readable.on (_stream_readable.js:689:33)
  at Socket.Stream.pipe (stream.js:65:8)
  at /Users/valentinleveque/Sites/maestro-mails/node_modules/grunt-premailer/tasks/premailer.js:132:30
  at /Users/valentinleveque/Sites/maestro-mails/node_modules/grunt-premailer/node_modules/async/lib/async.js:125:13
  at Array.forEach (native)
  at _each (/Users/valentinleveque/Sites/maestro-mails/node_modules/grunt-premailer/node_modules/async/lib/async.js:46:24)
  at Object.async.each (/Users/valentinleveque/Sites/maestro-mails/node_modules/grunt-premailer/node_modules/async/lib/async.js:124:9)
  at Object.<anonymous> (/Users/valentinleveque/Sites/maestro-mails/node_modules/grunt-premailer/tasks/premailer.js:95:15)
  at Object.<anonymous> (/Users/valentinleveque/Sites/maestro-mails/node_modules/grunt/lib/grunt/task.js:264:15)
  at Object.thisTask.fn (/Users/valentinleveque/Sites/maestro-mails/node_modules/grunt/lib/grunt/task.js:82:16)
  at Object.<anonymous> (/Users/valentinleveque/Sites/maestro-mails/node_modules/grunt/lib/util/task.js:301:30)
  at Task.runTaskFn (/Users/valentinleveque/Sites/maestro-mails/node_modules/grunt/lib/util/task.js:251:24)
  at Task.<anonymous> (/Users/valentinleveque/Sites/maestro-mails/node_modules/grunt/lib/util/task.js:300:12)
  at /Users/valentinleveque/Sites/maestro-mails/node_modules/grunt/lib/util/task.js:227:11
  at process._tickCallback (node.js:415:13)
```

And my generated file just got a doctype.

**Comment by nrambeck** [comment]
I'm getting this same error on the latest release (0.2.13).  Per the comment above, I changed the `async.eachLimit` concurrent operations value to 5 instead of 10 and the error went away.
